# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'GettingStartedWithKIF' do

end

target 'GettingStartedWithKIFTests' do

end

target 'UITests', :exclusive => true do
    pod 'KIF', '~> 3.0', :configurations => ['Debug']
end

